name: CI/CD

on:
  workflow_call:

env:
  FORCE_COLOR: 3 # Diplay chalk colors

jobs:
  ci:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - id: yarn-cache
        name: Get Yarn cache path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 16.x
      - uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0
        name: Load Yarn cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --ignore-scripts
        name: Install dependencies
      - run: yarn ci
        name: Run integration tests
      - uses: coverallsapp/github-action@50c33ad324a9902697adbf2f92c22cf5023eacf1
        name: Report code coverage
      - uses: 47ng/actions-slack-notify@main
        name: Notify on Slack
        if: always()
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  cd:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [ci]
    if: ${{ github.ref_name == 'main' || github.ref_name == 'beta' || github.ref_name == 'alpha' }}
    steps:
      - id: yarn-cache
        name: Get Yarn cache path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 16.x
      - uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0
        name: Load Yarn cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --ignore-scripts
        name: Install dependencies
      - run: yarn build
        name: Build package

      # Continuous Delivery Pipeline --

      - uses: docker://ghcr.io/codfish/semantic-release-action@sha256:16ab6c16b1bff6bebdbcc6cfc07dfafff49d23c6818490500b8edb3babfff29e
        name: Semantic Release
        id: semantic
        with:
          branches: |
            [
              'main',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
